# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_url', models.CharField(blank=True, max_length=128)),
                ('chords_url', models.CharField(blank=True, max_length=128)),
                ('tab_url', models.CharField(blank=True, max_length=128)),
                ('artist_name', models.CharField(blank=True, max_length=128)),
                ('song_title', models.CharField(blank=True, max_length=128)),
                ('album', models.CharField(blank=True, max_length=128)),
                ('spotify_track_id', models.CharField(blank=True, max_length=128)),
                ('youtube_video_id', models.CharField(blank=True, max_length=128)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tabs',
            },
        ),
    ]
