# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='spotify_album_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
