# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tab_spotify_album_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='art_url',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
